# Generated by Django 4.2.2 on 2023-10-09 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangapp', '0002_hake'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hake',
        ),
    ]
